### ISSUE TITLE
Xcode 9.3.1

### ISSUE THREAD

**Issue by ANLopatin** [SocketMobile/cocoapods-capture#1]
I have an error:
file is universal (4 slices) but does not contain a(n) armv7s architecture
when I try archiving build.
in podfile: 
  pod 'SKTCapture', '1.0.117'
What version of pod I should use?

**Comment by EricGlaenzer** [comment]
Can you update to the latest version? This build was done with the new Xcode 10 and had the arm architectures missing which has been fixed on the latest release of Capture.
