### ISSUE TITLE
Not working in simulator with xcode 12 beta

### ISSUE THREAD

**Issue by tmiedema** [SocketMobile/cocoapods-capture#16]
We're getting the error when were building in xcode 12 beta 4.

`In /Pods/SKTCapture/lib/libCaptureServiceDirect.a(SktCapture.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64`

**Comment by EricGlaenzer** [comment]
Hi Tom, 
Thank you for reporting this. We'll look at it and report back.

**Comment by sammcewan** [comment]
Put this on another framework to help out.

Promoted to a failure in Xcode 12 b5.

Needs to be distributed as an XCFramework or as uncompiled source.
https://developer.apple.com/forums/thread/657425?page=1#628116022
https://developer.apple.com/forums/thread/130684

**Comment by EricGlaenzer** [comment]
Did you have this error with a Xcode 11? The library file should support all iOS 2 processors, and x86 for the emulator.

**Comment by sammcewan** [comment]
@EricGlaenzer This would have manifested as a warning. From Xcode b4 it's it's now a failure. Apple's answer here was pretty comprehensive. https://developer.apple.com/forums/thread/130684 

> Having x86_64 code is not sufficient to distinguish if a binary is intended for the iOS Simulator, a macOS app, or a Mac Catalyst app. Combing built binaries across different destinations (which includes the simulator vs. device binaries) is not a supported combination -- there is no Apple platform where ARM code and x86_64 code in the same binary is a correct configuration.

For now we have removed the Socket framework from our Xcode 12 candidate.

**Comment by EricGlaenzer** [comment]
@sammcewan Thanks, we are looking into this and will get back to you as soon as we have something.

**Comment by tmiedema** [comment]
Are there any updates for this issue?

**Comment by EricGlaenzer** [comment]
We are still working on it. We should have something really soon.

**Comment by Errortype520** [comment]
Are there any updates to this?

**Comment by EricGlaenzer** [comment]
We are still working on this. At this time we don't know if we should continue with cocoapods or/and use Swift package.

**Comment by sammcewan** [comment]
Suggest SPM as a start if possible.

**Comment by Errortype520** [comment]
We are migrating from Carthage to SPM and had no intention of using cocoapods at all and are now running a separate branch. SPM seems like the logical choice moving forward IMO

**Comment by EricGlaenzer** [comment]
Thank you that's certainly balancing our choice toward SPM. Not certain how some external files (like our public key file) are handled yet with SPM.

**Comment by tmiedema** [comment]
SPM is not a possibility for us, but I've found a workaround. 

In the projects settings I have removed the 'VALID_ARCHS' under user defined. In the pod settings of SKTCapture, I only build the active architecture for a debug version. This way it will build for the simulator

**Comment by EricGlaenzer** [comment]
A new version of our SDK Capture has been released (1.2.187). This will require the new Cocoapods release 1.10.0 or higher.
A SPM version will be coming shortly.
This new version fully support now our new S550 NFC Contactless Reader/Writer especially when using large payload.
