### ISSUE TITLE
Target has transitive dependencies that include statically linked binaries: (SKTCapture)

### ISSUE THREAD

**Issue by chbeer** [SocketMobile/cocoapods-capture#19]
Trying to update `SKTCapture` Cocoapod to the newest version, I get the following error:

`[!] The 'Pods-Wildmarke dev' target has transitive dependencies that include statically linked binaries: (SKTCapture)`

`pod --version -> 1.10.0`

**Comment by EricGlaenzer** [comment]
Can you try the version 1.3.3 and report here?

**Comment by chbeer** [comment]
Installing SKTCapture 1.3.3 (was 1.2.36)
…
[!] The 'Pods-Wildannahme Bonkhoff' target has transitive dependencies that include statically linked binaries: (SKTCapture)

**Comment by EricGlaenzer** [comment]
Ok, it is true that SKTCapture is a static link library... Is your project where you include SKTCapture an App or another CocoaPods?

**Comment by Chrishon-Socket** [comment]
@chbeer If your project is also a Cocoapod that uses SKTCapture as a dependency then you may add this to your Podspec file:

```
 s.static_framework = true
```

**Comment by chbeer** [comment]
@EricGlaenzer sorry for my late answer.

It's a CocoaPod. We have a CocoaPod that we use in many apps to wrap all scanners we use (NFC, QR-Code, etc.) under one façade.

I think I made progress, now there's a new error message, resulting in the fact that I use an arm64 M1 mac:

`error: could not find module 'SKTCapture' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64`

Do you support that already? Or is there something wrong here?

**Comment by chbeer** [comment]
Credit where credit is due: the hint by @Chrishon-Socket was good. That seemed to have helped... but I'm couldn't verify yet because of the error above.

**Comment by chbeer** [comment]
Installing on device works. So that's good. Thanks @Chrishon-Socket!

But: installing on simulator on arm64 Macs (M1) doesn't work.
