### ISSUE TITLE
ld: symbol(s) not found for architecture armv7s

### ISSUE THREAD

**Issue by ANLopatin** [SocketMobile/cocoapods-capture#2]
Error while archiving project

**Comment by EricGlaenzer** [comment]
Can you add more details about your issue? What version of Capture, what is the error?

**Comment by ANLopatin** [comment]
<img width="537" alt="2018-11-19 18 46 10" src="https://user-images.githubusercontent.com/38750766/48721868-6a8a5680-ec2b-11e8-83c6-5c5c02b09aa1.png">

**Comment by ANLopatin** [comment]
Last version of Xcode & Capture
