### ISSUE TITLE
Provide binary for 'arm64-apple-ios-simulator' (M1 Macs)

### ISSUE THREAD

**Issue by chbeer** [SocketMobile/cocoapods-capture#20]
Error message when installing on simulator on M1:

`error: could not find module 'SKTCapture' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64`

**Comment by Chrishon-Socket** [comment]
Hi @chbeer we have scheduled this to be investigated tomorrow (Tuesday February 23 2021) and will give you an update on the matter.

**Comment by AlesMMichalek** [comment]
Hello. I did some experiments with new M1 Mac and SKTCapture library. I see there is xcframework with all supported platforms, but SKTCapture.podspec still contains EXCLUDED_ARCHS compilation option. I guess it should be removed to fully support simulator on Apple Silicon.
Please, could you check this settings? Thanks.

**Comment by ElviraBurchik** [comment]
Hello 👋  

I'd like to up this issue 🙂

 Do you need any help updating `EXCLUDED_ARCHS` section or maybe it's already somewhere in progress?

**Comment by EricGlaenzer** [comment]
The new version 1.3.133 fixes this issue.
