### ISSUE TITLE
Crash when disconnecting device

### ISSUE THREAD

**Issue by sammcewan** [SocketMobile/cocoapods-capture#23]
I've spent some time digging into a long running crash we've had at L1052 on CaptureHelper.swift

It's occurring just on disconnection because a class is being used as a key in the dictionary (which shouldn't be done) and my reading of the numerous crash logs is the memory is deallocated and `objectForKey:` is called on an unrelated object.

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1857939d8 __exceptionPreprocess
1  libobjc.A.dylib                0x199b16b54 objc_exception_throw
2  CoreFoundation                 0x1856a3bbc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x18579601c ___forwarding___
4  CoreFoundation                 0x185797f8c _CF_forwarding_prep_0
5  libswiftCore.dylib             0x18922f8d0 __CocoaDictionary.lookup(_:)
6  VendRegister                   0x105310da0 specialized Dictionary.subscript.getter
7  VendRegister                   0x10530ebb8 CaptureHelper.didReceive(_:for:withResult:) + 1052 (CaptureHelper.swift:1052)
8  VendRegister                   0x10531158c @objc CaptureHelper.didReceive(_:for:withResult:) (<compiler-generated>)
9  VendRegister                   0x10516e204 -[SKTCapture didReceiveEvent:withHandle:withResult:]
```

This is pretty painful for our end users, we'd love to see a resolution ASAP.

**Comment by Chrishon-Socket** [comment]
Hi @sammcewan 

We just merged a pull request #24 related to this issue. The keys of the offending dictionaries have been changed from an object to a String.

The pod has been pushed. Please let use know if you experience any further crashes related to this incident

Thank you.
