### ISSUE TITLE
Turn off annoying application logs [mot_LEConnectivityMgr startDiscovery] Discovery is not started due to incorrect central manager state

### ISSUE THREAD

**Issue by sofiialushchanets** [SocketMobile/cocoapods-capture#25]
Please add a possibility to turn off or remove completely ongoing library console logs like:
-[mot_SDKHandler sbtSetOperationalMode:] Remove incompatible devices for new op mode
-[mot_SDKHandler sbtEnableAvailableScannersDetection:] Perform discovering once option becomes enabled
-[mot_LEConnectivityMgr startDiscovery] Discovery is not started due to incorrect central manager state
etc..
Can't find any good way of removing those from our side. Also there is no solution for this suggested online... 
Those console logs are extremely annoying and obstruct from proper debugging with logs in console.
Please help!
Thank you in advance

**Comment by EricGlaenzer** [comment]
are you using the Zebra SDK? It seems these traces come from them... We don't have any functions named as mentioned above.

**Comment by sofiialushchanets** [comment]
Ah, I will double check this. Thank you for quick response! My apologies for any inconveniences.
