### ISSUE TITLE
Duplicate symbols hit when linking with -all_load

### ISSUE THREAD

**Issue by jerrymarino** [SocketMobile/cocoapods-capture#29]
Hello, I've hit a bunch of duplicate symbol issues when using `all_load` in an iOS app. It looks like the library has included duplicate symbols in a dependency (`test_*` files ), and finally in the file `SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc31f140a990de5f41f2f0e9201b1c27106.o`

```
duplicate symbol '_main' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Intermediates.noindex/SomeiOS.build/Debug-iphonesimulator/SomeiOS.build/Objects-normal/x86_64/main.o
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_compress.o)
duplicate symbol '_main' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Intermediates.noindex/SomeiOS.build/Debug-iphonesimulator/SomeiOS.build/Objects-normal/x86_64/main.o
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_compute.o)
duplicate symbol '_vli_print' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_compress.o)
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_compute.o)
duplicate symbol '_main' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Intermediates.noindex/SomeiOS.build/Debug-iphonesimulator/SomeiOS.build/Objects-normal/x86_64/main.o
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_ecdh.o)
duplicate symbol '_vli_print' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_compress.o)
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_ecdh.o)
duplicate symbol '_main' in:
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Intermediates.noindex/SomeiOS.build/Debug-iphonesimulator/SomeiOS.build/Objects-normal/x86_64/main.o
    /Users/jmarino/Library/Developer/Xcode/DerivedData/SomeiOS-fnhwwzgdzpnfzuhdsuoxbiwihdqg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SKTCapture/libCapture.a(test_ecdsa.o)
ld: 43 duplicate symbols for architecture x86_64
```

As a workaround I have attempted to remove the following object, but it'd be nice to have this in the SDK in general.:

```
  #.. 
   pushd /tmp/clean
   ar dv /tmp/${arch}_libCapture.a test_ecdsa.o 
   ar dv /tmp/${arch}_libCapture.a test_ecdh.o
   ar dv /tmp/${arch}_libCapture.a test_compress.o
   ar dv /tmp/${arch}_libCapture.a test_compute.o

   # This has 2 dupe objects in there, we might want to find out why.
   ar dv /tmp/${arch}_libCapture.a SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc31f140a990de5f41f2f0e9201b1c27106.o

  #...
```

**Comment by EricGlaenzer** [comment]
looks like the Capture SDK has been linked multiple times in your project.

**Comment by jerrymarino** [comment]
It's only linked 1 time, however the application is setting the `-all_load` linker flag, which means it loads all members of the archive:

```
     -all_load   Loads all members of static archive libraries.
```
Here, the issue arrises because there are test files are included from a dependency, and another duplicate object file `SktSoftScanDeviceObject`.

I've attached a reproduction of the issue to below
[cocoapods-capture-all_load_linking-problems.zip](https://github.com/SocketMobile/cocoapods-capture/files/6651951/cocoapods-capture-all_load_linking-problems.zip)

**Comment by EricGlaenzer** [comment]
Yes it's linked twice. If you go to SomeiOS/Pods in the project navigator, you will see `-l Capture` and  `-framework "SKTCapture"`
Did you install SKTCapture with an older version of cocoapods? The version that should be used is `1.10.x` or higher. (pod --version), if that's the case I recommend uninstalling SKTCapture, update cocoapods and then redo a pod install.

**Comment by EricGlaenzer** [comment]
@jerrymarino : did you get your issue fixed?

**Comment by jerrymarino** [comment]
@EricGlaenzer the issue I've got is with the link failing when using the linker flag `-all_load`. 
The static lib `lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a` contains multiple main functions:

Notice the multiple addresses for this function in the ouput of nm:
```
$ nm  Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a   | grep _main
0000000000000000 T _main
no symbols
0000000000004b38 S _OBJC_IVAR_$_SKTAppInfo._mainBundle
0000000000004b50 S _OBJC_IVAR_$_SKTCapture._mainCapture
no symbols
000000000000005c T _main
000000000000003e T _main
no symbols
000000000000005c T _main
                 U __dispatch_main_q

```

and duplicate symbols for `CSktSoftScanDeviceObject:*`

```
$ nm  Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a  | grep sendDecodedData
no symbols
0000000000002fda T __ZN24CSktSoftScanDeviceObject15sendDecodedDataEPKc23ESktCaptureDataSourceID
0000000000003bc0 s l___const._ZN24CSktSoftScanDeviceObject15sendDecodedDataEPKc23ESktCaptureDataSourceID.szUnknownSymbology
no symbols
no symbols
                 U __ZN24CSktSoftScanDeviceObject15sendDecodedDataEPKc23ESktCaptureDataSourceID
0000000000000276 T __ZN24CSktSoftScanDeviceObject15sendDecodedDataEPKc23ESktCaptureDataSourceID
```

Here's object files causing the issues to help debug it:
```
$ otool -L  Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a | grep SoftScanDevice
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc38805d4ee5f78e138421d06404d2d6a01.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc31f140a990de5f41f2f0e9201b1c27106.o):
$ otool -L  Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a | grep test
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_ecdsa.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_compress.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_ecdh.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_compute.o):
```
```
$ otool -L  Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a | grep test
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_ecdsa.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_compress.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_ecdh.o):
Pods/SKTCapture/lib/SKTCapture.xcframework/ios-arm64_i386_x86_64-simulator/libCapture.a(test_compute.o):
```


The issue is there isn't a great way to fix the static library in this repo. Mainly it's unclear what the side effects are of removing either one of the object files named `SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc31f140a990de5f41f2f0e9201b1c27106.o` or `SktSoftScanDeviceObject-12682b31f1c785896e0c5573fe86bbc38805d4ee5f78e138421d06404d2d6a01.`  I can assume the test objects were from a dependency and it's ok to remove those.

**Comment by jerrymarino** [comment]
> You should not remove anything and bear in mind in the .a file you have multiple libraries since they support multiple processor.

The addresses nm shows are for each architecture, so even if you thin the file they are the same. Other than post-processing the `.a` what is the recommendation to use `libCapture.a` in an app that needs `-all_load`?



Here's the pod version, but I don't know if it'd change the file I'm running:
```
$ pod --version
1.10.1
```

I just followed the instructions to add this pod to an app via Podfile and ran `pod install`
```
$ cat Podfile
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SomeiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SKTCapture', '= 1.3.33'
end
```
I bet the main difference is I  have `-all_load` in my linker flags. It works fine without passing `-all_load` but I need this flag for the rest of the app right now

**Comment by jerrymarino** [comment]
<img width="1768" alt="DiagramOfLinkerInvocation" src="https://user-images.githubusercontent.com/1245820/122277130-66358100-ce9a-11eb-87c2-8d0100c3832e.png">

**Comment by EricGlaenzer** [comment]
![Screen Shot 2021-06-16 at 3 13 01 PM](https://user-images.githubusercontent.com/3876881/122279000-90486c80-ceb5-11eb-8e0a-28bbb0dfbc76.png)

**Comment by EricGlaenzer** [comment]
This is compiling and linking. I also update to SKTCapture version `1.3.60`

**Comment by EricGlaenzer** [comment]
Looking more into this, you do need the libraries as configured in the project settings when installing the Capture cocoapods. I am not sure why/where are the duplicates coming from by example for the SoftScanDevice stuff. Let me dig some more into this.

**Comment by jerrymarino** [comment]
@EricGlaenzer thanks kindly for looking into this.

Here is [a workaround script I hacked together, fix_libCapture.a.sh.zip](https://github.com/SocketMobile/cocoapods-capture/files/6672989/fix_libCapture.a.sh.zip). This one post-process this the to remove redundant symbols, if it's helpful for anyone else or to help debug the issue

**Comment by socketPM** [comment]
@jerrymarino It's been a while. In case you are interested, we finally fixed this issue. We are running a beta version to test. You can get more details here: https://github.com/SocketMobile/capturesdk_flutter_snapshot/issues/1#issuecomment-1105493131

**Comment by cyrille-socket** [comment]
Hi @jerrymarino, we have updated our SDK to the new [CaptureSDK](https://github.com/SocketMobile/cocoapods-capturesdk).
It solves your issue. Please let us know if it works for you.
If not, please create an issue in the new [CaptureSDK](https://github.com/SocketMobile/cocoapods-capturesdk) repository.
