### ISSUE TITLE
Non-portable path to file '<SKTCapture/SktCapture.h>'

### ISSUE THREAD

**Issue by psycrtb** [SocketMobile/cocoapods-capture#3]
This is a minor issue but one you may want to be aware of. There is a naming convention issue with the SKTCapture.h file. 
The import defines it as <SKTCapture/SKTCapture.h> but a warning describes it as a 'non-portable path to the file <SKTCapture/SktCapture.h>.

Its probably because you're using a case insensitive OS file system to build the SDK where as my OS file system is case sensitive. 

Heres an example of a similar issue on a similar project:
https://github.com/BranchMetrics/ios-branch-deep-linking/issues/559

I am using SKTCapture 1.1.33 installed via cocoapods. Build env is iOS 10+ and im using Xcode 10.1

**Comment by KsAvsFan** [comment]
I'm having the exact same issue.  Is there a workaround?

**Comment by EricGlaenzer** [comment]
We are looking into this issue, and hopefully have a fix for it very soon

**Comment by KsAvsFan** [comment]
@EricGlaenzer  - Any updates on this?

**Comment by EricGlaenzer** [comment]
Yes we have a fix for it, but we are still in the process of releasing a new version of this Cocoapods. Hopefully should be done in the next few days.

**Comment by EricGlaenzer** [comment]
A new version of the Cocoapods Capture for Objective C has been released that fixes this issue. Version 1.1.148
