### ISSUE TITLE
[__NSCFString substringWithRange:] Range out of bounds error

### ISSUE THREAD

**Issue by Lixivial** [SocketMobile/cocoapods-capture#33]
We are trying to implement the Capture SDK in a Flutter app via a Swift plugin. The Capture SDK is installed via Cocoapods, and when trying to open a connection to the scanner, we receive the following error while calling `CaptureHelper.openWithAppInfo`:

```
2021-11-30 15:04:51.488127-0600 Runner[931:525073] Capture version 1.3.60.260
2021-11-30 15:04:51.497210-0600 Runner[931:525234] *** -[__NSCFString substringWithRange:]: Range {9223372036854775811, 9223372036854775924} out of bounds; string length 146. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
Runner(931,0x16f9e3000) malloc: can't allocate region
*** mach_vm_map(size=9223372036854792192) failed (error code=3)
Runner(931,0x16f9e3000) malloc: *** set a breakpoint in malloc_error_break to debug
2021-11-30 15:04:51.497696-0600 Runner[931:525234] Incorrect size found for the public key: 0
Result of Capture initialization: -93
```

There's not much interesting in the way we instantiate and call this; mostly lifted from the sample code:

```
_captureHelper = CaptureHelper.sharedInstance
if let helper = _captureHelper {
        helper.pushDelegate(self)
        helper.dispatchQueue = DispatchQueue.main
        let appInfo = SKTAppInfo()

        appInfo.developerID = Bundle.main.object(forInfoDictionaryKey: "SocketCaptureDevId") as? String ?? ""
        appInfo.appID = Bundle.main.object(forInfoDictionaryKey: "SocketCaptureBundleId") as? String ?? ""
        appInfo.appKey = Bundle.main.object(forInfoDictionaryKey: "SocketCaptureAppKey") as? String ?? ""
        
        // open Capture Helper only once in the application
        helper.openWithAppInfo(appInfo, withCompletionHandler: {(result: SKTResult) in print("Result of Capture initialization: \(result.rawValue)")})
}
```

In `CaptureHelper.openWithAppInfo()`'s `completionHandler`, the `SKTResult` ends up being `E_INVALIDAPPINFO`, which results in the connection never being completed.

Our `appKey`, `appID`, `developerID` come from an `xcconfig` mapped thru `Info.plist`, but I've also simply hardcoded those properties with our values as well as the sample values provided in the sample documentation to rule out any of that mapping. I've also tried setting `AppInfo.mainBundle` so that it could check our `Info.plist`, and that check succeeds -- we have all the appropriate access protocols defined. 

Our app's minimum deployment target is iOS 12.0, as well.

EDIT:

Just noting that I get similar when running the sample app from https://github.com/SocketMobile/capturesingleentry-ios albeit this is using an older version and using the Objective-C SDK:

```
2021-12-01 11:18:33.773867-0600 SingleEntry[257:9647] Capture version 1.2.36.181
2021-12-01 11:18:33.781592-0600 SingleEntry[257:9827] *** -[__NSCFString substringWithRange:]: Range {9223372036854775811, 9223372036854775924} out of bounds; string length 146. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
SingleEntry(257,0x16f043000) malloc: can't allocate region
*** mach_vm_map(size=9223372036854792192) failed (error code=3)
SingleEntry(257,0x16f043000) malloc: *** set a breakpoint in malloc_error_break to debug
2021-12-01 11:18:33.781851-0600 SingleEntry[257:9827] Incorrect size found for the public key: 0
2021-12-01 11:18:33.783122-0600 SingleEntry[257:9827] Opening Capture returns: -93
```

**Comment by socketPM** [comment]
@Lixivial this looks like a pure App Info issue. Have you ever applied the same app info any other way, i.e. is this a proven working appkey/dev id/bundle ID combination? We occasionally produce AppKeys that do not have the right number of characters. Please send an email to developers[at]socketmobile[dot]com (with your registered email account or other info that we can identify your account) so we can take a look. Thanks.

**Comment by Lixivial** [comment]
@socketPM no, none of them are proven to be working, but in the case of the sample project [capturesingleentry-ios](https://github.com/SocketMobile/capturesingleentry-ios ,) I just checked it out and built it with whatever sample AppInfo was supplied there. I also tried all the of the supplied sample app key/dev id/bundle ID combinations I could find in the sample documentation.

I assumed that at least one of those would be working out of the box. Without the ability to glean a lot of insight beyond the error code, I began to suspect the `[__NSCFString substringWithRange]` error was at play, since the length matched the length of the `socketmobilepublickey.pem` provided, but yet...

> 2021-12-01 11:18:33.781851-0600 SingleEntry[257:9827] Incorrect size found for the public key: 0

it was reported to be 0. I will send an email to diagnose further.

**Comment by EricGlaenzer** [comment]
@Lixivial looking at the traces in this thread, it seems Capture cannot find the public key file. Do you have it in your package?

**Comment by Lixivial** [comment]
@EricGlaenzer, I suspected that, too. The error definitely seemed to imply an inability to read the public key correctly.

I checked the pod and it's definitely in the `Resources` dir. Upon initial run of `pod install`, its target membership is not in any specific project (though I tried adding checking those for `Pods-Runner` and `SKTCapture` to no avail). Here's a screenshot of my current settings on that:

![image](https://user-images.githubusercontent.com/33925/144473169-344c3ac8-ed85-4c37-9911-f5a4299cdbd8.png)

I went so far as to install the SDK manually and I encountered the same issue. I also validated the contents of the .pem file and the checksums match up with what's in GitHub here, so I don't think it's corrupted.

**Comment by EricGlaenzer** [comment]
When you install the pod, it should be in the Resources like you mentioned. But when you build the app, it should be in the bundle of the app. Did you check it there? (if I remember correctly, for a Swift app or ObjectiveC app, the project setting will copy the softScanBeep.wav and the socketmobilepublickey.pem into the app resources.

**Comment by EricGlaenzer** [comment]
If you look at the package content of one of our SingleEntry apps you should see something like this:
![Screen Shot 2021-12-02 at 1 12 38 PM](https://user-images.githubusercontent.com/3876881/144479606-d69e8cce-6595-4f95-b232-36d562a22632.png)

**Comment by Lixivial** [comment]
@EricGlaenzer, sorry, no I hadn't looked, but it is indeed there:

Here's our app:
![image](https://user-images.githubusercontent.com/33925/144496263-f1dfc4b2-cca5-48ec-a810-80ef6a25b685.png)

The SingleEntry sample I built yesterday:
![image](https://user-images.githubusercontent.com/33925/144496385-4adcefb6-f7e5-4693-82d4-ef3a9411e036.png)

**Comment by EricGlaenzer** [comment]
@Lixivial yes the sample apps work, and it does require new AppKey. If you change the bundle ID of the SingleEntry app then you will need to generate new App Keys from our developer portal. I tried yesterday, and if the app key is incorrect the message in the logs really show an issue with the AppKey, not with the public key.

**Comment by Lixivial** [comment]
Good to know. Does that mean I should generate a new AppKey for the sample app in the dev portal and adjust the code for my dev ID, and the new app key? In my tests I'd performed no modifications to the sample apps and I'd received the same error I reported. I simply checked them out, compiled and ran them assuming the AppInfo in there was fine. But I can give that a try.

But, like you said, I would expect a message in the logs about the AppKey if that were the issue. If that test doesn't work, is there possibly anything in my environment that might affect this? I'm on Xcode 13.1 on macOS 11.5.1 on an Intel Mac. As far as I can tell, this is all handled in the `libCapture` static lib and I can't imagine anything in my env affecting that, but just trying to rule things out.

**Comment by socketPM** [comment]
@Lixivial replacing the app info with the one you created for your own app (as you mentioned in your email) should work. Maybe just create another key and try again?

**Comment by socketPM** [comment]
Wait, sorry, the issue with that one is that the bundle ID is not the sample app's bundle id, so you do need to create a new one using the sample apps bundle id, unless you change the sample's bundle ID to use your own app's bundle ID. @EricGlaenzer can correct me if that's not true...

**Comment by EricGlaenzer** [comment]
The AppKey will verify if the bundle ID of your app matches with the one provided during the AppKey generation.

**Comment by Lixivial** [comment]
OK, finally had a chance to revisit this. I went through all our AppKeys and generating a new AppKey solved it. This can be closed.

**Comment by EricGlaenzer** [comment]
Glad you have it solved. Thanks for letting us know. Don't hesitate to contact us in case something else comes up.

**Comment by Lixivial** [comment]
Ah, sorry, I spoke too soon. I was in the middle of debugging and _thought_ it was working, but was deceived because the scanner beeped and I didn't hit an error. But that was just the general scanner connecting to iOS after power on.

Anyway, I've created a new AppKey and tried _all_ of my AppKeys & Bundle IDs in my app and the sample app and I still get the same error I reported above. I even tried the latest version 1.3.133.792.

```
2021-12-07 14:39:23.372777-0600 Runner[659:149555] Capture version 1.3.133.792
2021-12-07 14:39:23.376500-0600 Runner[659:149675] *** -[__NSCFString substringWithRange:]: Range {9223372036854775811, 9223372036854775924} out of bounds; string length 146. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
Runner(659,0x16f41f000) malloc: can't allocate region
*** mach_vm_map(size=9223372036854792192) failed (error code=3)
Runner(659,0x16f41f000) malloc: *** set a breakpoint in malloc_error_break to debug
2021-12-07 14:39:23.376743-0600 Runner[659:149675] Incorrect size found for the public key: 0
Result of Capture initialization: -93
```

**Comment by EricGlaenzer** [comment]
Looking at the code, to display this trace, it means that the public key file is present, we can open it, we have either an issue to read the content of the file or the file format is not what is expected. I am guess you've have just copied over the public key file, but just to double check can you make sure the size of this pem file is 142 bytes.

**Comment by Lixivial** [comment]
OK, @EricGlaenzer, that definitely had me double checking my verification I did previously and, yeah, you're right. The file in my workspace was 146b, the file in GitHub and elsewhere is 142b.

So I pulled a clean `.ipa` off our build server and compared it to the file here on GitHub as well as the pulled down 1.3.133.792 podfile in my workspace. The workspace file is 146b and one sourced directly from github and the build server's ipa are 142b:

```
-rw-r--r--  1 jpearson  wheel   142B Dec  8 10:54 /Users/jpearson/Downloads/github-socketmobilepublickey.pem
-rw-r--r--@ 1 jpearson  staff   142B Dec  7 16:31 /Users/jpearson/Downloads/Payload/Runner.app/socketmobilepublickey.pem
-rw-r--r--  1 jpearson  staff   146B Dec  7 12:17 /Users/jpearson/workspace/jumpstock/case-companion/ios/Pods/SKTCapture/socketmobilepublickey.pem
5acbe62b728a86e5591c025c55c4d588  /Users/jpearson/Downloads/github-socketmobilepublickey.pem
5acbe62b728a86e5591c025c55c4d588  /Users/jpearson/Downloads/Payload/Runner.app/socketmobilepublickey.pem
650c0743b0b53ed0c7bd949a2a95aa6a  /Users/jpearson/workspace/jumpstock/case-companion/ios/Pods/SKTCapture/socketmobilepublickey.pem

When I cat them out with `cat -e`, I can see some odd line ending differences:
```
/Users/jpearson/Downloads/github-socketmobilepublickey.pem:
-----BEGIN PUBLIC KEY-----$
MD4wEAYHKoZIzj0CAQYFK4EEAAgDKgAEpYrGTsC/uNrcr6qUAN0U4Scy4/9Zx5sT$
wfkQAYDtEyTCETFswgHLNQ==$
-----END PUBLIC KEY-----$

 /Users/jpearson/Downloads/Payload/Runner.app/socketmobilepublickey.pem:
-----BEGIN PUBLIC KEY-----$
MD4wEAYHKoZIzj0CAQYFK4EEAAgDKgAEpYrGTsC/uNrcr6qUAN0U4Scy4/9Zx5sT$
wfkQAYDtEyTCETFswgHLNQ==$
-----END PUBLIC KEY-----$

/Users/jpearson/workspace/jumpstock/case-companion/ios/Pods/SKTCapture/socketmobilepublickey.pem:
-----BEGIN PUBLIC KEY-----^M$
MD4wEAYHKoZIzj0CAQYFK4EEAAgDKgAEpYrGTsC/uNrcr6qUAN0U4Scy4/9Zx5sT^M$
wfkQAYDtEyTCETFswgHLNQ==^M$
-----END PUBLIC KEY-----^M$
```

So line endings got mangled at some point. I cleared my pod cache and reran `pod install` and now the pem file has the correct size, md5 checksum and everything works just fine. 

```
2021-12-08 11:47:45.571947-0600 Runner[786:168459] Capture version 1.3.133.792
Result of Capture initialization: 0
```

Oof, that was a journey. Thanks for the assistance; I think this can _now_ be closed.

**Comment by EricGlaenzer** [comment]
No worries, I am glad you've it working now. Let us know if we can assist you further.
