### ISSUE TITLE
CaptureHelper.handleDeviceDidReceiveDecodedData Crash

### ISSUE THREAD

**Issue by BarryDuggan** [SocketMobile/cocoapods-capture#34]
SDK 1.3.133

SDK crashes after `CaptureHelper.didReceive` is called at the `CaptureHelper.handleDeviceDidReceiveDecodedData `switch case.
My best guess for this is because `CaptureHelper.handleDeviceDidReceiveDecodedData` checks to see if there is a delegate but then uses the delegate in an async call.

By the time the async method gets called the delegate could be nil.
This is resulting in a `EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000`

Here is the 'potentially' [offending line of code](https://github.com/SocketMobile/cocoapods-capture/blob/eed075cb04ce1674ee541c2ce76c5582eae8bced/CaptureHelper.swift#L1076)

A possible solution to this is to not bother with the check for delegate before the async call and use optional chaining instead.
That way you are guaranteed that the memory address of the delegate is valid at the 'actual' time of invocation.

### Stack Trace

```
Crashed: NSOperationQueue 0x133f55950 (QOS: UNSPECIFIED)
0  TOFS_AppStore                  0x6605c0 CaptureHelper.handleDeviceDidReceiveDecodedData(capture:event:result:) + 4378002880 (<compiler-generated>:4378002880)
1  TOFS_AppStore                  0x65f0b8 CaptureHelper.didReceive(_:for:withResult:) + 954 (CaptureHelper.swift:954)
2  TOFS_AppStore                  0x65f340 @objc CaptureHelper.didReceive(_:for:withResult:) + 4377998144 (<compiler-generated>:4377998144)
3  TOFS_AppStore                  0x57ca58 -[SKTCapture didReceiveEvent:withHandle:withResult:] + 4377070168
4  TOFS_AppStore                  0x5a63c4 -[SKTCaptureServiceDirect consumeFromCaptureHandle:] + 4377240516
5  TOFS_AppStore                  0x5a66e0 __72-[SKTCaptureServiceDirect doConsumeFromCaptureHandle:completionHandler:]_block_invoke + 4377241312
6  Foundation                     0x132f88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
7  Foundation                     0x20628 -[NSBlockOperation main] + 104
8  Foundation                     0x1353b0 __NSOPERATION_IS_INVOKING_MAIN__ + 24
9  Foundation                     0x202b0 -[NSOperation start] + 808
10 Foundation                     0x135e54 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
11 Foundation                     0x1358e0 __NSOQSchedule_f + 184
12 libdispatch.dylib              0x13484 _dispatch_block_async_invoke2 + 148
13 libdispatch.dylib              0x481c _dispatch_client_callout + 20
14 libdispatch.dylib              0x7cf4 _dispatch_continuation_pop + 448
15 libdispatch.dylib              0x7384 _dispatch_async_redirect_invoke + 592
16 libdispatch.dylib              0x15fe0 _dispatch_root_queue_drain + 388
17 libdispatch.dylib              0x167d8 _dispatch_worker_thread2 + 112
18 libsystem_pthread.dylib        0x3768 _pthread_wqthread + 216
19 libsystem_pthread.dylib        0xa74c start_wqthread + 8
```

**Comment by BarryDuggan** [comment]
It looks like this could be a duplicate of [this issue](https://github.com/SocketMobile/cocoapods-capture/issues/28#issue-878076919)

**Comment by cyrille-socket** [comment]
Hi @BarryDuggan
We will analyse this and get back to you with a fix. Your guess on the potential line of code causing this issue seems accurate. IT will be fixed in the next version of the SDK that should be released soon.

**Comment by cyrille-socket** [comment]
Hi @BarryDuggan, we have updated our SDK to the new CaptureSDK containing CaptureHelper [here](https://github.com/SocketMobile/cocoapods-capturesdk).
It solves your issue and the duplicate issue too.
Please let us know if it works for you.
If not, please create an issue in the new [CaptureSDK](https://github.com/SocketMobile/cocoapods-capturesdk) repository.
