### ISSUE TITLE
Add swift version to the podspec file.

### ISSUE THREAD

**Issue by russelh15** [SocketMobile/cocoapods-capture#6]
As of Cocoapods 1.7.x, .swift-version files are deprecated.

http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

Can you add the `s.swift_version` to the podspec file?

I tried creating a PR, but got permission denied.

**Comment by EricGlaenzer** [comment]
@russelh15 Good point and thank you for reporting this. We will fix this shortly. A new version will be available this week.

**Comment by rajubd49** [comment]
Any update on "Add swift version to the podspec file."?

**Comment by EricGlaenzer** [comment]
@rajubd49 We are still working on releasing the new version of Capture for Swift. Sorry, this is taking more time than originally thought in part because we are adding new features.

**Comment by Chrishon-Socket** [comment]
@russelh15 @rajubd49 `s.swift_version` has been added to the podspec file as of the latest version: `1.1.351`. Again, we apologize for the delay.
